from pyspark.sql import types as T

final_schema = T.StructType([
    T.StructField('conciliation_id', T.StringType(), True),
    T.StructField('count_retry', T.StringType(), True),
    T.StructField('creation_date', T.StringType(), True),
    T.StructField('creation_date_tstamp', T.TimestampType(), True),
    T.StructField('customer_apellido1', T.StringType(), True),
    T.StructField('customer_apellido2', T.StringType(), True),
    T.StructField('customer_celular', T.StringType(), True),
    T.StructField('customer_cif_id', T.StringType(), True),
    T.StructField('customer_correo_electronico', T.StringType(), True),
    T.StructField('customer_document_id', T.StringType(), True),
    T.StructField('customer_estado_id', T.StringType(), True),
    T.StructField('customer_fecha_expedicion', T.TimestampType(), True),
    T.StructField('customer_fecha_nacimiento', T.TimestampType(), True),
    T.StructField('customer_is_full_sign_up', T.StringType(), True),
    T.StructField('customer_is_use_regulation', T.StringType(), True),
    T.StructField('customer_nombre1', T.StringType(), True),
    T.StructField('customer_nombre2', T.StringType(), True),
    T.StructField('customer_numero_cuenta', T.StringType(), True),
    T.StructField('customer_numero_id', T.StringType(), True),
    T.StructField('customer_tipo_id', T.StringType(), True),
    T.StructField('customer_user_creation', T.StringType(), True),
    T.StructField('message_id', T.StringType(), True),
    T.StructField('order_bene_document_id', T.StringType(), True),
    T.StructField('order_bene_document_type', T.StringType(), True),
    T.StructField('order_bene_first_name', T.StringType(), True),
    T.StructField('order_bene_last_name', T.StringType(), True),
    T.StructField('order_bene_last_name2', T.StringType(), True),
    T.StructField('order_bene_remittances_id', T.StringType(), True),
    T.StructField('order_bene_second_name', T.StringType(), True),
    T.StructField('order_beneficiary_amount', T.StringType(), True),
    T.StructField('order_beneficiary_currency', T.StringType(), True),
    T.StructField('order_country_from', T.StringType(), True),
    T.StructField('order_date', T.TimestampType(), True),
    T.StructField('order_date_timestamp', T.TimestampType(), True),
    T.StructField('order_exchange_rate', T.StringType(), True),
    T.StructField('order_full_response', T.StringType(), True),
    T.StructField('order_mobile_wallet_account_no', T.StringType(), True),
    T.StructField('order_mobile_wallet_prefix', T.StringType(), True),
    T.StructField('order_order_no', T.StringType(), True),
    T.StructField('order_payer_document_id', T.StringType(), True),
    T.StructField('order_payer_document_type', T.StringType(), True),
    T.StructField('order_payer_first_name', T.StringType(), True),
    T.StructField('order_payer_last_name', T.StringType(), True),
    T.StructField('order_payer_last_name2', T.StringType(), True),
    T.StructField('order_payer_remittances_id', T.StringType(), True),
    T.StructField('order_payer_second_name', T.StringType(), True),
    T.StructField('order_payment_amount', T.StringType(), True),
    T.StructField('order_payment_currency', T.StringType(), True),
    T.StructField('order_remittance_id', T.StringType(), True),
    T.StructField('order_sales_date', T.TimestampType(), True),
    T.StructField('order_id', T.StringType(), True),
    T.StructField('phone_number', T.StringType(), True),
    T.StructField('remittance_id', T.StringType(), True),
    T.StructField('state_cause', T.StringType(), True),
    T.StructField('state_code', T.StringType(), True),
    T.StructField('state_date', T.TimestampType(), True),
    T.StructField('state_date_tstamp', T.TimestampType(), True),
    T.StructField('state_status', T.StringType(), True),
    T.StructField('state_step', T.StringType(), True),
    T.StructField('state_order_steps', T.ArrayType(
        T.StructType([
            T.StructField('date', T.StringType(), True),
            T.StructField('date_t_stamp', T.StringType(), True),
            T.StructField('order_step', T.StringType(), True),
        ])
    , False), True),
    T.StructField('id_reward', T.StringType(), False),
    #T.StructField('flag_event_status', T.StringType(), False), # Only if you have active event_status
])
